{% set version = "0.1.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-yulab.utils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/yulab.utils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yulab.utils/yulab.utils_{{ version }}.tar.gz
  sha256: d958877ee9b1bebedeb6e3bb5f19e8df6dce85eb637a89b0d4a583ee60bf3e9f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-digest
    - r-fs
    - r-httr2
    - r-rlang
  run:
    - r-base
    - r-cli
    - r-digest
    - r-fs
    - r-httr2
    - r-rlang

test:
  commands:
    - $R -e "library('yulab.utils')"           # [not win]
    - "\"%R%\" -e \"library('yulab.utils')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=yulab.utils
  license: Artistic-2.0
  summary: Miscellaneous functions commonly used by 'YuLab-SMU', such as 'install_zip_gh' to install R package from github zip file, 'o' to open selected directory and file.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
